language: rust
rust:
  - 1.36.0

cache: cargo

before_script:
  - rustup component add rustfmt

script:
  - cargo build --verbose --release --all
  - cargo fmt --all -- --check
  - cargo test --verbose --release --all
